enum Dep {
    private enum Versions {
        static final kotlin = "1.2.70"
        static final gradlePlugin = "3.2.0-rc03"
        static final supportLib = "28.0.0-rc02"
        static final constraintLayout = "1.1.3"
        static final glide = "4.8.0"
        static final markwon = "1.1.1"
        static final okHttp = "3.11.0"
        static final retrofit = "2.4.0"
        static final rxAndroid = "2.1.0"
        static final rxJava = "2.2.2"
        static final stetho = "1.5.0"
        static final gson = "2.8.5"
        static final timber = "4.7.1"
        static final room = "1.1.1"
        static final jUnit = "4.12"
        static final testRunner = "1.0.1"
        static final espresso = "3.0.1"
    }

    static final kotlinLib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    static final supportAppcompat = "com.android.support:appcompat-v7:${Versions.supportLib}"
    static final cardView = "com.android.support:cardview-v7:${Versions.supportLib}"
    static final glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    static final glideProcessor = "com.github.bumptech.glide:compiler:${Versions.glide}"
    static final supportDesign = "com.android.support:design:${Versions.supportLib}"
    static final supportCustomTabs = "com.android.support:customtabs:${Versions.supportLib}"
    static final constraintLayout = "com.android.support.constraint:constraint-layout:${Versions.constraintLayout}"
    static final markwon = "ru.noties:markwon:${Versions.markwon}"
    static final markwonImageLoader = "ru.noties:markwon-image-loader:${Versions.markwon}"
    static final okHttpLogger = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttp}"
    static final retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    static final retrofitRxAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    static final retrofitGsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    static final rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    static final rxJava = "io.reactivex.rxjava2:rxjava:${Versions.rxJava}"
    static final stetho = "com.facebook.stetho:stetho:${Versions.stetho}"
    static final stethoOkHttp = "com.facebook.stetho:stetho-okhttp3:${Versions.stetho}"
    static final gson = "com.google.code.gson:gson:${Versions.gson}"
    static final timber = "com.jakewharton.timber:timber:${Versions.timber}"
    static final room = "android.arch.persistence.room:runtime:${Versions.room}"
    static final roomProcessor = "android.arch.persistence.room:compiler:${Versions.room}"
    static final roomRxSupport = "android.arch.persistence.room:rxjava2:${Versions.room}"

    static final jUnit = "junit:junit:${Versions.jUnit}"
    static final testRunner = "com.android.support.test:runner:${Versions.testRunner}"
    static final espresso = "com.android.support.test.espresso:espresso-core:${Versions.espresso}"

    static final kotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    static final gradlePlugin = "com.android.tools.build:gradle:${Versions.gradlePlugin}"
}
