enum Dep {
    private enum Versions {
        static final androidx = "1.0.0"
        static final androidxArch = "2.0.0"
        static final constraintLayout = "1.1.3"
        static final espresso = "3.1.0"
        static final glide = "4.8.0"
        static final gradlePlugin = "3.2.1"
        static final gson = "2.8.5"
        static final jUnit = "4.12"
        static final kotlin = "1.3.0"
        static final kotlinxCoroutines = "1.0.1"
        static final markwon = "2.0.0"
        static final materialComponents = "1.0.0"
        static final okHttp = "3.11.0"
        static final retrofit = "2.4.0"
        static final room = "2.0.0"
        static final rxAndroid = "2.1.0"
        static final rxJava = "2.2.3"
        static final stetho = "1.5.0"
        static final testRunner = "1.1.0"
        static final timber = "4.7.1"
    }

    static final androidxAppCompat = "androidx.appcompat:appcompat:${Versions.androidx}"
    static final androidxBrowser = "androidx.browser:browser:${Versions.androidx}"
    static final androidxCardView = "androidx.cardview:cardview:${Versions.androidx}"
    static final androidxExtensions = "androidx.lifecycle:lifecycle-extensions:${Versions.androidxArch}"
    static final constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    static final glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    static final glideProcessor = "com.github.bumptech.glide:compiler:${Versions.glide}"
    static final gson = "com.google.code.gson:gson:${Versions.gson}"
    static final kotlinLib = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.kotlin}"
    static final kotlinCoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.kotlinxCoroutines}"
    static final kotlinCoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.kotlinxCoroutines}"
    static final kotlinCoroutinesRx = "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:${Versions.kotlinxCoroutines}"
    static final markwon = "ru.noties:markwon:${Versions.markwon}"
    static final markwonImageLoader = "ru.noties:markwon-image-loader:${Versions.markwon}"
    static final materialComponents = "com.google.android.material:material:${Versions.materialComponents}"
    static final okHttpLogger = "com.squareup.okhttp3:logging-interceptor:${Versions.okHttp}"
    static final retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    static final retrofitRxAdapter = "com.squareup.retrofit2:adapter-rxjava2:${Versions.retrofit}"
    static final retrofitGsonConverter = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    static final room = "androidx.room:room-runtime:${Versions.room}"
    static final roomProcessor = "androidx.room:room-compiler:${Versions.room}"
    static final roomRxSupport = "androidx.room:room-rxjava2:${Versions.room}"
    static final rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.rxAndroid}"
    static final rxJava = "io.reactivex.rxjava2:rxjava:${Versions.rxJava}"
    static final stetho = "com.facebook.stetho:stetho:${Versions.stetho}"
    static final stethoOkHttp = "com.facebook.stetho:stetho-okhttp3:${Versions.stetho}"
    static final timber = "com.jakewharton.timber:timber:${Versions.timber}"

    static final jUnit = "junit:junit:${Versions.jUnit}"
    static final testRunner = "androidx.test.runner:${Versions.testRunner}"
    static final espresso = "androidx.test.espresso:espresso-core:${Versions.espresso}"

    static final kotlinPlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    static final gradlePlugin = "com.android.tools.build:gradle:${Versions.gradlePlugin}"
}
