include(
    ":app",
    ":dynamic-list-adapter",
    ":dynamic-list-adapter-extensions",
    ":dynamic-list-adapter-viewbinding",
    ":markdown",
    ":markdown-compose",
    ":markdown-compose-demo",
    ":stackexchange-api"
)
