include(
    ":app",
    ":compose-markdown",
    ":compose-markdown-demo",
    ":compose-preference",
    ":dynamic-list-adapter",
    ":dynamic-list-adapter-extensions",
    ":dynamic-list-adapter-viewbinding",
    ":markdown",
    ":stackexchange-api"
)
