[versions]
about-libraries = "10.10.0"
android-gradlePlugin = "8.2.2"
androidx-activity = "1.8.2"
androidx-appcompat = "1.6.1"
androidx-benchmark-baselineProfile-gradlePlugin = "1.2.3"
androidx-benchmark-macro-junit4 = "1.2.3"
androidx-browser = "1.7.0"
androidx-compose-foundation = "1.6.1"
androidx-compose-compiler = "1.5.9"
androidx-compose-material = "1.6.1"
androidx-compose-material3 = "1.2.0"
androidx-compose-runtime = "1.6.1"
androidx-compose-ui = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-core = "1.12.0"
androidx-fragment = "1.6.2"
androidx-hilt = "1.1.0"
androidx-lifecycle = "2.7.0"
androidx-preference = "1.2.1"
androidx-profileinstaller = "1.3.1"
androidx-recyclerview = "1.3.2"
androidx-room = "2.6.1"
androidx-security = "1.1.0-alpha06"
androidx-swiperefreshlayout = "1.1.0"
androidx-test-core = "1.5.0"
androidx-test-runner = "1.5.2"
androidx-test-ext = "1.1.5"
androidx-uiautomator = "2.2.0"
androidx-viewpager2 = "1.1.0-beta02"
androidx-work = "2.9.0"
apache-commons-text = "1.10.0"
barista = "4.2.0"
betterlinkmovementmethod = "2.2.0"
chucker = "4.0.0"
coil = "2.5.0"
dagger = "2.50"
detekt = "1.19.0"
espresso = "3.5.1"
google-firebase-bom = "32.7.2"
google-firebase-crashlytics-gradle = "2.9.9"
google-ksp = "1.9.22-1.0.17"
google-material = "1.11.0"
google-play-appUpdate = "2.1.0"
google-play-billing = "6.1.0"
google-play-review = "2.0.1"
google-services = "4.4.1"
insetter = "0.6.1"
javaPoet = "1.13.0"
jetbrains-kotlin = "1.9.22"
jetbrains-kotlinx-coroutines = "1.8.0"
jetbrains-markdown = "0.4.1"
junit = "4.13.2"
klock = "3.4.0"
ktlint-gradle = "11.4.0"
markwon = "4.6.2"
metalava-gradle = "0.3.5"
mockito-core = "4.2.0"
mockito-kotlin = "4.0.0"
moshi = "1.15.1"
okhttp = "5.0.0-alpha.12"
prism4j = "2.0.0"
process-phoenix = "2.1.1"
retrofit = "2.9.0"
robolectric = "4.11.1"
timber = "5.0.1"

[plugins]
google-dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }

[libraries]
aboutLibraries-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "about-libraries"}
aboutLibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "about-libraries" }
aboutLibraries-gradlePlugin = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "about-libraries" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "android-gradlePlugin" }

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-benchmark-baselineProfile-gradlePlugin = { group = "androidx.benchmark", name = "benchmark-baseline-profile-gradle-plugin", version.ref = "androidx-benchmark-baselineProfile-gradlePlugin" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "androidx-benchmark-macro-junit4" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "androidx-compose-foundation" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "androidx-compose-runtime" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "androidx-compose-material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-ui" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "androidx-profileinstaller" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "androidx-security" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core" }
androidx-test-ext = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-uiautomator" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager2" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work"}

apache-commonsText = { module = "org.apache.commons:commons-text", version.ref = "apache-commons-text" }

barista = { module = "com.adevinta.android:barista", version.ref = "barista" }

betterlinkmovementmethod = { module = "me.saket:better-link-movement-method", version.ref = "betterlinkmovementmethod" }

chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso" }

google-dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
google-dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "google-firebase-bom"}
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
google-firebase-crashlytics-gradlePlugin = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "google-firebase-crashlytics-gradle" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-play-appUpdate = { module = "com.google.android.play:app-update-ktx", version.ref = "google-play-appUpdate" }
google-play-billing = { module = "com.android.billingclient:billing-ktx", version.ref = "google-play-billing" }
google-play-review = { module = "com.google.android.play:review-ktx", version.ref = "google-play-review" }
google-services-gradlePlugin = { module = "com.google.gms:google-services", version.ref = "google-services" }

insetter = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }

javaPoet = { module = "com.squareup:javapoet", version.ref = "javaPoet" }

jetbrains-kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }
jetbrains-kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "jetbrains-kotlinx-coroutines" }
jetbrains-markdown = { module = "org.jetbrains:markdown", version.ref = "jetbrains-markdown" }

junit = { module = "junit:junit", version.ref = "junit" }

klock = { module = "com.soywiz.korlibs.klock:klock", version.ref = "klock" }

ktlint-gradlePlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint-gradle" }

markwon-core = { module = "io.noties.markwon:core", version.ref = "markwon" }
markwon-html = { module = "io.noties.markwon:html", version.ref = "markwon" }
markwon-imageCoil = { module = "io.noties.markwon:image-coil", version.ref = "markwon" }
markwon-inlineParser = { module = "io.noties.markwon:inline-parser", version.ref = "markwon" }
markwon-latex = { module = "io.noties.markwon:ext-latex", version.ref = "markwon" }
markwon-linkify = { module = "io.noties.markwon:linkify", version.ref = "markwon" }
markwon-strikethrough = { module = "io.noties.markwon:ext-strikethrough", version.ref = "markwon" }
markwon-syntaxhighlight = { module = "io.noties.markwon:syntax-highlight", version.ref = "markwon" }
markwon-tables = { module = "io.noties.markwon:ext-tables", version.ref = "markwon" }
markwon-tasklist = { module = "io.noties.markwon:ext-tasklist", version.ref = "markwon" }

metalava-gradlePlugin = { module = "me.tylerbwong.gradle.metalava:plugin", version.ref = "metalava-gradle" }

mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }

moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlinCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }

prism4jBundler = { module = "io.noties:prism4j-bundler", version.ref = "prism4j" }

processPhoenix = { module = "com.jakewharton:process-phoenix", version.ref = "process-phoenix" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
